# ───────────────────────────────────────────────
#  Local Helper — Configuration
#  Fill in your credentials below.
# ───────────────────────────────────────────────

# ── AI Proxy ──────────────────────────────────────────────
BASE_URL = "https://YOUR_PROXY_URL/v1"   # <-- replace with your proxy base URL
API_KEY  = "YOUR_API_KEY"                 # <-- replace with your proxy API key

# Default model (must be supported by your proxy)
DEFAULT_MODEL = "claude-sonnet-4.6"

# Available models shown in the UI dropdown
AVAILABLE_MODELS = [
    "claude-opus-4.6",
    "claude-sonnet-4.6",
    "claude-sonnet-4.5",
    "claude-opus-4.5",
    "claude-haiku-4.5",
    "gpt-5.4",
    "gpt-5.2",
    "gpt-4.1",
    "gemini-3-pro-preview",
    "gemini-2.5-pro",
]

# ── GitHub ──────────────────────────────────────────────
GITHUB_TOKEN = ""   # <-- your GitHub classic token (starts with ghp_)

# ── Dropbox ──────────────────────────────────────────────
# Run setup_dropbox.py ONCE to generate these values.
DROPBOX_APP_KEY       = ""   # <-- from Dropbox App Console
DROPBOX_APP_SECRET    = ""   # <-- from Dropbox App Console
DROPBOX_REFRESH_TOKEN = ""   # <-- generated by setup_dropbox.py (never expires)

# ── App Settings ────────────────────────────────────────────
# Web search results count (3–5 recommended)
WEB_SEARCH_RESULTS = 5

# GUI layout: "Tabbed" (top tab bar) or "Sidebar" (left icon rail)
GUI_LAYOUT = "Tabbed"

# Database file
DB_PATH = "local_helper.db"

# Space files directory (synced with Dropbox if tokens are set)
FILES_DIR = "space_files"

# Templates directory
TEMPLATES_DIR = "templates"

# ── Translation ──────────────────────────────────────────────
# Primary translation backend: "libretranslate" or "google"
# libretranslate = self-hosted, private, no internet needed when running
# google         = always-on online fallback via deep-translator (no key needed)
TRANSLATE_BACKEND = "libretranslate"

# LibreTranslate server URL (self-hosted; change to VPS address when ready)
LIBRETRANSLATE_URL = "http://localhost:5000"

# Default target language for the translate panel
TRANSLATE_TARGET_LANG = "en"
