"""Dropbox integration — sync local space_files folder with Dropbox.

Uses a permanent refresh token (generated by setup_dropbox.py).
Falls back to a short-lived access token if only DROPBOX_ACCESS_TOKEN is set.
"""

import os
from config import (
    DROPBOX_APP_KEY, DROPBOX_APP_SECRET,
    DROPBOX_REFRESH_TOKEN, FILES_DIR
)

try:
    import dropbox
    from dropbox.exceptions import ApiError
    DROPBOX_AVAILABLE = True
except ImportError:
    DROPBOX_AVAILABLE = False


def _get_client():
    if not DROPBOX_AVAILABLE:
        raise RuntimeError("dropbox package not installed. Run: pip install dropbox")

    if DROPBOX_REFRESH_TOKEN and DROPBOX_APP_KEY and DROPBOX_APP_SECRET:
        # Permanent connection via refresh token (recommended)
        return dropbox.Dropbox(
            app_key=DROPBOX_APP_KEY,
            app_secret=DROPBOX_APP_SECRET,
            oauth2_refresh_token=DROPBOX_REFRESH_TOKEN
        )

    raise RuntimeError(
        "Dropbox credentials not configured.\n"
        "Run setup_dropbox.py to generate your tokens, "
        "then paste them into config.py."
    )


def is_configured() -> bool:
    """Returns True if Dropbox credentials are set in config."""
    return bool(DROPBOX_AVAILABLE and DROPBOX_REFRESH_TOKEN and DROPBOX_APP_KEY)


def upload_file(local_path: str, dropbox_path: str = None) -> bool:
    """Upload a single local file to Dropbox.

    Args:
        local_path:    Full local path to file.
        dropbox_path:  Destination path in Dropbox.
                       Defaults to '/local_helper/<filename>'.
    Returns:
        True on success, False on failure.
    """
    if not os.path.exists(local_path):
        return False
    if dropbox_path is None:
        filename = os.path.basename(local_path)
        dropbox_path = f"/local_helper/{filename}"
    try:
        dbx = _get_client()
        with open(local_path, "rb") as f:
            dbx.files_upload(
                f.read(),
                dropbox_path,
                mode=dropbox.files.WriteMode.overwrite
            )
        return True
    except Exception:
        return False


def sync_folder(local_folder: str = FILES_DIR, dropbox_folder: str = "/local_helper") -> dict:
    """Upload all files in local_folder to Dropbox.

    Returns:
        Dict with 'uploaded' and 'failed' lists.
    """
    result = {"uploaded": [], "failed": []}
    if not os.path.exists(local_folder):
        os.makedirs(local_folder, exist_ok=True)
    for fname in os.listdir(local_folder):
        local_path = os.path.join(local_folder, fname)
        if os.path.isfile(local_path):
            dropbox_path = f"{dropbox_folder}/{fname}"
            ok = upload_file(local_path, dropbox_path)
            (result["uploaded"] if ok else result["failed"]).append(fname)
    return result


def download_file(dropbox_path: str, local_path: str) -> bool:
    """Download a file from Dropbox to a local path."""
    try:
        dbx = _get_client()
        _, res = dbx.files_download(dropbox_path)
        os.makedirs(os.path.dirname(local_path), exist_ok=True)
        with open(local_path, "wb") as f:
            f.write(res.content)
        return True
    except Exception:
        return False


def list_remote_files(dropbox_folder: str = "/local_helper") -> list[str]:
    """List all files in a Dropbox folder.

    Returns:
        List of file names, or empty list on error.
    """
    try:
        dbx = _get_client()
        result = dbx.files_list_folder(dropbox_folder)
        return [entry.name for entry in result.entries
                if isinstance(entry, dropbox.files.FileMetadata)]
    except Exception:
        return []
